spring:
  application:
    name: gomall-auth-server
  redis:
    host: 39.99.246.104
    port: 6379
    password: 990326bai
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
  #sessiong相关配置
  session:
    #将session保存到redis中
    store-type: redis
    #session过期时间
    timeout: 30m
server:
  port: 20000

