spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  alicloud:
    sms:
      host: https://gyytz.market.alicloudapi.com
      path: /sms/smsSend
      appcode: f88fdea5a7eb466c950ab1a9f9f0ddc0
      smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
      templateId: 908e94ccf08b4476ba6c876d13f084ad
server:
  port: 30000

